# Generated by Django 5.1.1 on 2024-10-15 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='laptop',
            name='rating',
            field=models.IntegerField(default=4),
        ),
    ]
