# Generated by Django 5.1.1 on 2024-10-16 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_laptop_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='laptop',
            name='display',
            field=models.DecimalField(decimal_places=2, default=15.6, max_digits=10),
        ),
        migrations.AddField(
            model_name='laptop',
            name='ram',
            field=models.IntegerField(default=8),
        ),
    ]
