# Generated by Django 5.1.1 on 2024-10-16 14:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0003_laptop_display_size_laptop_ram"),
    ]

    operations = [
        migrations.AlterField(
            model_name="laptop",
            name="display_size",
            field=models.DecimalField(
                decimal_places=1,
                default=15.6,
                help_text="Display size in inches",
                max_digits=4,
            ),
        ),
        migrations.AlterField(
            model_name="laptop",
            name="ram",
            field=models.IntegerField(default=8, help_text="RAM size in GB"),
        ),
    ]
