# Generated by Django 5.1.1 on 2024-10-16 17:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0004_alter_laptop_display_size_alter_laptop_ram"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="laptop",
            name="display_size",
        ),
        migrations.AddField(
            model_name="laptop",
            name="display",
            field=models.DecimalField(decimal_places=2, default=15.6, max_digits=10),
        ),
        migrations.AlterField(
            model_name="laptop",
            name="ram",
            field=models.IntegerField(default=8),
        ),
    ]
