# Generated by Django 5.1.1 on 2024-10-16 18:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0005_remove_laptop_display_size_laptop_display_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="laptop",
            name="ram",
            field=models.IntegerField(default=8, help_text="RAM size in GB"),
        ),
    ]
